version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data:/var/lib/postgresql/data 
    network_mode: "host"
  admin:
    image: dpage/pgadmin4:4
    environment:
      PGADMIN_LISTEN_PORT: "15432"
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - db
    network_mode: "host"
